//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorINT.AreasServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AreasServiceReference.AreasWebServiceSoap")]
    public interface AreasWebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento AreaCirculoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo", ReplyAction="*")]
        CalculatorINT.AreasServiceReference.AreaCirculoResponse AreaCirculo(CalculatorINT.AreasServiceReference.AreaCirculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorINT.AreasServiceReference.AreaCirculoResponse> AreaCirculoAsync(CalculatorINT.AreasServiceReference.AreaCirculoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento AreaCuadradoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCuadrado", ReplyAction="*")]
        CalculatorINT.AreasServiceReference.AreaCuadradoResponse AreaCuadrado(CalculatorINT.AreasServiceReference.AreaCuadradoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCuadrado", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorINT.AreasServiceReference.AreaCuadradoResponse> AreaCuadradoAsync(CalculatorINT.AreasServiceReference.AreaCuadradoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento AreaTrianguloResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaTriangulo", ReplyAction="*")]
        CalculatorINT.AreasServiceReference.AreaTrianguloResponse AreaTriangulo(CalculatorINT.AreasServiceReference.AreaTrianguloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaTriangulo", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorINT.AreasServiceReference.AreaTrianguloResponse> AreaTrianguloAsync(CalculatorINT.AreasServiceReference.AreaTrianguloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AreaCirculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AreaCirculo", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorINT.AreasServiceReference.AreaCirculoRequestBody Body;
        
        public AreaCirculoRequest() {
        }
        
        public AreaCirculoRequest(CalculatorINT.AreasServiceReference.AreaCirculoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AreaCirculoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float R;
        
        public AreaCirculoRequestBody() {
        }
        
        public AreaCirculoRequestBody(float R) {
            this.R = R;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AreaCirculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AreaCirculoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorINT.AreasServiceReference.AreaCirculoResponseBody Body;
        
        public AreaCirculoResponse() {
        }
        
        public AreaCirculoResponse(CalculatorINT.AreasServiceReference.AreaCirculoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AreaCirculoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AreaCirculoResult;
        
        public AreaCirculoResponseBody() {
        }
        
        public AreaCirculoResponseBody(string AreaCirculoResult) {
            this.AreaCirculoResult = AreaCirculoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AreaCuadradoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AreaCuadrado", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorINT.AreasServiceReference.AreaCuadradoRequestBody Body;
        
        public AreaCuadradoRequest() {
        }
        
        public AreaCuadradoRequest(CalculatorINT.AreasServiceReference.AreaCuadradoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AreaCuadradoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int L;
        
        public AreaCuadradoRequestBody() {
        }
        
        public AreaCuadradoRequestBody(int L) {
            this.L = L;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AreaCuadradoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AreaCuadradoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorINT.AreasServiceReference.AreaCuadradoResponseBody Body;
        
        public AreaCuadradoResponse() {
        }
        
        public AreaCuadradoResponse(CalculatorINT.AreasServiceReference.AreaCuadradoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AreaCuadradoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AreaCuadradoResult;
        
        public AreaCuadradoResponseBody() {
        }
        
        public AreaCuadradoResponseBody(string AreaCuadradoResult) {
            this.AreaCuadradoResult = AreaCuadradoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AreaTrianguloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AreaTriangulo", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorINT.AreasServiceReference.AreaTrianguloRequestBody Body;
        
        public AreaTrianguloRequest() {
        }
        
        public AreaTrianguloRequest(CalculatorINT.AreasServiceReference.AreaTrianguloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AreaTrianguloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float B;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float A;
        
        public AreaTrianguloRequestBody() {
        }
        
        public AreaTrianguloRequestBody(float B, float A) {
            this.B = B;
            this.A = A;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AreaTrianguloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AreaTrianguloResponse", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorINT.AreasServiceReference.AreaTrianguloResponseBody Body;
        
        public AreaTrianguloResponse() {
        }
        
        public AreaTrianguloResponse(CalculatorINT.AreasServiceReference.AreaTrianguloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AreaTrianguloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AreaTrianguloResult;
        
        public AreaTrianguloResponseBody() {
        }
        
        public AreaTrianguloResponseBody(string AreaTrianguloResult) {
            this.AreaTrianguloResult = AreaTrianguloResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AreasWebServiceSoapChannel : CalculatorINT.AreasServiceReference.AreasWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AreasWebServiceSoapClient : System.ServiceModel.ClientBase<CalculatorINT.AreasServiceReference.AreasWebServiceSoap>, CalculatorINT.AreasServiceReference.AreasWebServiceSoap {
        
        public AreasWebServiceSoapClient() {
        }
        
        public AreasWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AreasWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreasWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreasWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorINT.AreasServiceReference.AreaCirculoResponse CalculatorINT.AreasServiceReference.AreasWebServiceSoap.AreaCirculo(CalculatorINT.AreasServiceReference.AreaCirculoRequest request) {
            return base.Channel.AreaCirculo(request);
        }
        
        public string AreaCirculo(float R) {
            CalculatorINT.AreasServiceReference.AreaCirculoRequest inValue = new CalculatorINT.AreasServiceReference.AreaCirculoRequest();
            inValue.Body = new CalculatorINT.AreasServiceReference.AreaCirculoRequestBody();
            inValue.Body.R = R;
            CalculatorINT.AreasServiceReference.AreaCirculoResponse retVal = ((CalculatorINT.AreasServiceReference.AreasWebServiceSoap)(this)).AreaCirculo(inValue);
            return retVal.Body.AreaCirculoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorINT.AreasServiceReference.AreaCirculoResponse> CalculatorINT.AreasServiceReference.AreasWebServiceSoap.AreaCirculoAsync(CalculatorINT.AreasServiceReference.AreaCirculoRequest request) {
            return base.Channel.AreaCirculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorINT.AreasServiceReference.AreaCirculoResponse> AreaCirculoAsync(float R) {
            CalculatorINT.AreasServiceReference.AreaCirculoRequest inValue = new CalculatorINT.AreasServiceReference.AreaCirculoRequest();
            inValue.Body = new CalculatorINT.AreasServiceReference.AreaCirculoRequestBody();
            inValue.Body.R = R;
            return ((CalculatorINT.AreasServiceReference.AreasWebServiceSoap)(this)).AreaCirculoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorINT.AreasServiceReference.AreaCuadradoResponse CalculatorINT.AreasServiceReference.AreasWebServiceSoap.AreaCuadrado(CalculatorINT.AreasServiceReference.AreaCuadradoRequest request) {
            return base.Channel.AreaCuadrado(request);
        }
        
        public string AreaCuadrado(int L) {
            CalculatorINT.AreasServiceReference.AreaCuadradoRequest inValue = new CalculatorINT.AreasServiceReference.AreaCuadradoRequest();
            inValue.Body = new CalculatorINT.AreasServiceReference.AreaCuadradoRequestBody();
            inValue.Body.L = L;
            CalculatorINT.AreasServiceReference.AreaCuadradoResponse retVal = ((CalculatorINT.AreasServiceReference.AreasWebServiceSoap)(this)).AreaCuadrado(inValue);
            return retVal.Body.AreaCuadradoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorINT.AreasServiceReference.AreaCuadradoResponse> CalculatorINT.AreasServiceReference.AreasWebServiceSoap.AreaCuadradoAsync(CalculatorINT.AreasServiceReference.AreaCuadradoRequest request) {
            return base.Channel.AreaCuadradoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorINT.AreasServiceReference.AreaCuadradoResponse> AreaCuadradoAsync(int L) {
            CalculatorINT.AreasServiceReference.AreaCuadradoRequest inValue = new CalculatorINT.AreasServiceReference.AreaCuadradoRequest();
            inValue.Body = new CalculatorINT.AreasServiceReference.AreaCuadradoRequestBody();
            inValue.Body.L = L;
            return ((CalculatorINT.AreasServiceReference.AreasWebServiceSoap)(this)).AreaCuadradoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorINT.AreasServiceReference.AreaTrianguloResponse CalculatorINT.AreasServiceReference.AreasWebServiceSoap.AreaTriangulo(CalculatorINT.AreasServiceReference.AreaTrianguloRequest request) {
            return base.Channel.AreaTriangulo(request);
        }
        
        public string AreaTriangulo(float B, float A) {
            CalculatorINT.AreasServiceReference.AreaTrianguloRequest inValue = new CalculatorINT.AreasServiceReference.AreaTrianguloRequest();
            inValue.Body = new CalculatorINT.AreasServiceReference.AreaTrianguloRequestBody();
            inValue.Body.B = B;
            inValue.Body.A = A;
            CalculatorINT.AreasServiceReference.AreaTrianguloResponse retVal = ((CalculatorINT.AreasServiceReference.AreasWebServiceSoap)(this)).AreaTriangulo(inValue);
            return retVal.Body.AreaTrianguloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorINT.AreasServiceReference.AreaTrianguloResponse> CalculatorINT.AreasServiceReference.AreasWebServiceSoap.AreaTrianguloAsync(CalculatorINT.AreasServiceReference.AreaTrianguloRequest request) {
            return base.Channel.AreaTrianguloAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorINT.AreasServiceReference.AreaTrianguloResponse> AreaTrianguloAsync(float B, float A) {
            CalculatorINT.AreasServiceReference.AreaTrianguloRequest inValue = new CalculatorINT.AreasServiceReference.AreaTrianguloRequest();
            inValue.Body = new CalculatorINT.AreasServiceReference.AreaTrianguloRequestBody();
            inValue.Body.B = B;
            inValue.Body.A = A;
            return ((CalculatorINT.AreasServiceReference.AreasWebServiceSoap)(this)).AreaTrianguloAsync(inValue);
        }
    }
}
